version: "3.7"

services:
    app:
        image: ricardomaximino/app:local
        build:
          context: ./
          dockerfile: ./app/docker/Dockerfile
          args:
            - NAME=app
            - VERSION=local
        environment:
          - SPRING_PROFILES_ACTIVE=local
        ports:
          - "8080:8080"
        volumes:
          - type: volume
            source: logs
            target: /logs
            volume:
              nocopy: true
        networks:
          - brasajava
        depends_on:
          - logstash          
        container_name: app
#docker run -d -h elasticsearch --name elasticsearch --net brasajava -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.5.1
    elasticsearch:
        image: elasticsearch:7.5.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        volumes:
          - "data:/usr/share/elasticsearch/data"
        networks:
            - brasajava
        
        container_name: elasticsearch
    kibana:
#docker run -d -p 5601:5601 -h kibana --name kibana --net brasajava --link elasticsearch_elasticsearch kibana:7.5.1    
        image: kibana:7.5.1
        ports:
            - "5601:5601"
        networks:
            - brasajava
        depends_on:
            - elasticsearch
        container_name: kibana
    logstash:
#docker run --rm -it --name logstash --net brasajava --link elasticsearch:elasticsearch -v ./logstash/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:7.5.1    
        image: logstash:local
        build:
            context: ./
            dockerfile: ./logstash/Dockerfile
        command: logstash -f /usr/share/logstash/logstash.conf
        networks:
            - brasajava
        depends_on:
            - elasticsearch
        container_name: logstash
    filebeat:
        image: filebeat:local
        build:
            context: ./
            dockerfile: ./filebeat/Dockerfile
        volumes:
            - logs:/usr/share/filebeat/logs
        networks:
            - brasajava
        depends_on:
            - app
        container_name: filebeat
    
volumes:
    logs:
    data:
        
networks:
    brasajava:
        driver: bridge